export const activationCopy = {
  ru: {
    eyebrow: 'Life OS · настройка системы',
    prototypeNote: 'Интерактивный прототип · данные не сохраняются',
    progress: 'Шаг {current} из {total}',
    back: 'Назад',
    next: 'Продолжить',
    finish: 'Вернуться в начало',
    required: 'Ответьте на вопрос, чтобы система могла продолжить настройку.',
    phases: [
      { title: 'Вход', detail: 'Контекст и готовность' },
      { title: 'Диагностика', detail: 'Поведение, саботаж, отвлечения' },
      { title: 'Профиль', detail: 'Ёмкость и уровень нагрузки' },
      { title: 'Система', detail: 'Цель недели и первый день' },
      { title: 'Первый цикл', detail: 'Фокус, разбор, адаптация' },
    ],
    stepNames: [
      'Регистрация',
      'Готовность',
      'Реальный ритм',
      'Саботаж',
      'Отвлечения',
      'Ёмкость',
      'Профиль',
      'Режим',
      'Цель недели',
      'Первый день',
      'Фокус',
      'Разбор',
      'Адаптация',
    ],
    entry: {
      label: 'Сначала — честная точка старта',
      title: 'Система Вашей Дисциплины',
      text: 'Life OS сначала изучает ваш ритм, отвлечения и реальную ёмкость. Затем предлагает нагрузку, которую можно удержать, и пересматривает её по фактам каждого дня.',
      valueTitle: 'Что произойдёт после регистрации',
      values: [
        'Вы пройдёте глубокую диагностику без оценки и стыда.',
        'Получите объяснимый профиль дисциплины и стартовый режим.',
        'Соберёте цель недели, первый день и проведёте фокус-сессию.',
      ],
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      password: 'Пароль',
      passwordPlaceholder: 'Минимум 8 символов',
      consent: 'Я понимаю, что изменение требует честных ответов и личного действия.',
      privacy: 'В прототипе форма не создаёт аккаунт и никуда не отправляет данные.',
    },
    commitment: {
      label: 'Контракт с собой',
      title: 'Система покажет. Действовать — вам.',
      text: 'Life OS не обещает мотивацию по нажатию кнопки. Она ограничивает перегрузку, возвращает к фактам и предлагает следующий посильный шаг.',
      agreement: 'Я готов отвечать о себе честно, даже если ответ мне не нравится.',
      principles: [
        { title: 'Самоконтроль', text: 'Замечать импульс отвлечься до автоматического действия.' },
        { title: 'Ответственность', text: 'Разделять внешние обстоятельства и собственное избегание.' },
        { title: 'Мягкая точность', text: 'Снижать нагрузку без самооправдания и повышать только по устойчивым фактам.' },
      ],
    },
    reality: {
      label: 'Диагностика · реальный ритм',
      title: 'Сколько дней живёт ваш план?',
      text: 'Нужен обычный месяц, а не лучший период вашей жизни.',
      options: [
        { id: 'rare', title: 'Почти никогда', text: 'Обычно срываюсь в первые 1–2 дня.' },
        { id: 'sometimes', title: 'Иногда', text: 'Могу держаться несколько дней, затем теряю ритм.' },
        { id: 'often', title: 'Часто', text: 'Структура держится, но ломается при перегрузке.' },
        { id: 'stable', title: 'Стабильно', text: 'Большинство недель закрываю по плану.' },
      ],
    },
    sabotage: {
      label: 'Диагностика · саботаж',
      title: 'Как вы саботируете старт?',
      text: 'Можно выбрать несколько вариантов. Здесь нет «правильного» ответа.',
      options: [
        { id: 'delay', title: 'Откладываю старт', text: 'Жду подходящего состояния или свободного окна.' },
        { id: 'perfectionism', title: 'Усложняю задачу', text: 'Поднимаю планку и не начинаю, пока не готов идеально.' },
        { id: 'planning', title: 'Продолжаю планировать', text: 'Уточняю систему вместо первого необратимого действия.' },
        { id: 'learning', title: 'Изучаю вместо практики', text: 'Открываю материалы по теме, хотя следующий шаг уже понятен.' },
        { id: 'switch', title: 'Берусь за другое', text: 'Закрываю мелочи, чтобы чувствовать занятость.' },
        { id: 'overload', title: 'Планирую больше ёмкости', text: 'Составляю день, который невозможно выполнить целиком.' },
      ],
    },
    distractions: {
      label: 'Диагностика · внимание',
      title: 'Что крадёт ваш фокус?',
      text: 'Отметьте даже те отвлечения, которые выглядят полезными.',
      options: [
        { id: 'gadget', title: 'Телефон и уведомления', text: 'Беру устройство без срочной причины.' },
        { id: 'social', title: 'Ленты и сообщения', text: 'Переключаюсь на социальные и информационные площадки.' },
        { id: 'research', title: 'Информация по теме', text: 'Ищу ещё один материал вместо выполнения уже понятного шага.' },
        { id: 'otherTasks', title: 'Другие дела', text: 'Перескакиваю на новую задачу до завершения текущей.' },
        { id: 'busywork', title: 'Имитация занятости', text: 'Сортирую, оформляю и настраиваю вместо результата.' },
        { id: 'internal', title: 'Внутренний шум', text: 'Ухожу в мысли, тревогу или оценку качества.' },
      ],
    },
    capacity: {
      label: 'Диагностика · ёмкость',
      title: 'Сколько фокуса вы реально выдержите?',
      text: 'Мы не ищем ваш максимум. Нужен объём, который можно повторить завтра.',
      focus: 'Один блок без отвлечений',
      daily: 'Весь продуктивный объём дня',
      minutes: '{value} мин',
      energyTitle: 'Обычный уровень энергии',
      energy: [
        { id: 'low', title: 'Низкий', text: 'Часто начинаю уже уставшим.' },
        { id: 'variable', title: 'Нестабильный', text: 'Сильно зависит от дня и нагрузки.' },
        { id: 'stable', title: 'Устойчивый', text: 'Обычно могу планировать ресурс заранее.' },
      ],
    },
    profile: {
      label: 'Профиль дисциплины',
      dominantLabel: 'Доминирующий профиль',
      basisTitle: 'Основание расчёта',
      title: 'Легче амбиций. Строже привычек.',
      text: 'Это не диагноз личности. Это рабочая конфигурация, собранная из ваших ответов.',
      profiles: {
        depleted: { name: 'Режим низкого ресурса', insight: 'Главное ограничение сейчас — доступная энергия. Первый режим должен восстановить ресурс и сохранить минимальный обязательный шаг.', scenario: { start: 'Один обязательный шаг на 10 минут. Остальное — только после него.', focus: 'Убрать уведомления и пройти один короткий блок без попытки догнать весь план.', setback: 'Не компенсировать объём: вернуться к минимальному шагу и восстановлению.' } },
        overloaded: { name: 'Перегруженный систематизатор', insight: 'Планка и объём сейчас выше устойчивой ёмкости. Первый режим должен сократить нагрузку и вернуть повторяемость без отказа от результата.', scenario: { start: 'Выбрать один внешний результат и удалить всё, что не ведёт к нему сегодня.', focus: 'Не более двух блоков; новые задачи записывать, но не переключаться на них.', setback: 'Сократить объём, а не продлевать день и не наказывать себя.' } },
        avoidant: { name: 'Осторожный стартер', insight: 'Главный разрыв возникает до начала действия. Первый режим должен уменьшить порог старта и закрепить короткий обязательный шаг.', scenario: { start: 'Начать действие в течение пяти минут без дополнительной подготовки.', focus: 'Первый блок короткий; оценивать факт старта, а не качество результата.', setback: 'Сделать двухминутный вход и зафиксировать, что именно остановило.' } },
        perfectionist: { name: 'Перфекционист на старте', insight: 'Требование сделать правильно повышает порог начала. Первый режим должен заранее определить достаточно хороший результат и ограничить подготовку.', scenario: { start: 'Заранее определить критерий «достаточно хорошо» и отправляемый результат.', focus: 'Ограничить подготовку таймером, затем обязательно перейти к черновику.', setback: 'Уменьшить стандарт качества, а не переносить действие целиком.' } },
        analytical: { name: 'Исследователь перед стартом', insight: 'Подготовка и поиск информации начинают заменять выполнение. Первый режим должен отделить полезное исследование от уже понятного действия.', scenario: { start: 'Оставить только один вопрос, который действительно блокирует действие.', focus: 'Исследование — максимум 10 минут; затем создать первый проверяемый фрагмент.', setback: 'Не искать новую методику: вернуться к уже понятному следующему действию.' } },
        busywork: { name: 'Занятость без результата', insight: 'Активность уходит в оформление, сортировку и мелкие дела. Первый режим должен требовать один внешний проверяемый результат вместо ощущения занятости.', scenario: { start: 'Назвать один результат, который можно показать другому человеку.', focus: 'Мелкие дела и оформление запрещены до появления основного результата.', setback: 'Удалить одну псевдозадачу и вернуть время в главный результат.' } },
        fragmented: { name: 'Фрагментированный исполнитель', insight: 'Вы способны действовать, но внимание распадается между переключениями. Первый режим должен убрать лишние входы и оставить один видимый результат.', scenario: { start: 'Закрыть лишние вкладки и оставить один канал, один документ и одну задачу.', focus: 'Телефон вне доступа; импульс переключиться отмечать, но не выполнять.', setback: 'Сократить следующий блок и убрать источник последнего отвлечения.' } },
        building: { name: 'Формирующий ритм', insight: 'Одного доминирующего сбоя нет, но ритм ещё не стал повторяемым. Первый режим должен закрепить простую опору и проверить её устойчивость.', scenario: { start: 'Закрепить одно постоянное время и один повторяемый первый шаг.', focus: 'Сохранять одинаковую структуру блока три дня, не усложняя систему.', setback: 'Вернуться к последней выполненной версии режима без новых правил.' } },
        stable: { name: 'Устойчивый исполнитель', insight: 'Ритм, энергия и ёмкость уже позволяют работать системно. Первый режим может быть интенсивнее, но повышение всё равно подтверждается фактами.', scenario: { start: 'Выбрать один приоритетный результат и заблокировать под него основной интервал.', focus: 'Полный блок без уведомлений; сложность повышать только после устойчивых дней.', setback: 'Сохранить ритм, снизив объём на один шаг, а не отменяя день.' } },
      },
      markers: {
        rhythm: 'Реальный ритм',
        sabotage: 'Саботаж',
        distractions: 'Отвлечения',
        capacity: 'Ресурс',
      },
      more: 'ещё {count}',
      capacityEvidence: '{energy} · {focus} мин / {daily} мин',
      insightTitle: 'Главное наблюдение',
      scenarioTitle: 'Как Life OS изменит ваш старт',
      scenarioLabels: { start: 'Первое действие', focus: 'Защита фокуса', setback: 'Если день сорвётся' },
    },
    program: {
      label: 'Рекомендация системы',
      title: 'Сложнее — не значит серьёзнее.',
      text: 'Рекомендуемый режим рассчитан из текущей ёмкости. Повышение произойдёт только после устойчивых фактов.',
      recommended: 'Рекомендовано',
      selected: 'Выбрано',
      modes: {
        gentle: { title: 'Мягкий вход', text: 'Вернуть повторяемость и убрать перегрузку.' },
        base: { title: 'Базовый ритм', text: 'Укрепить дисциплину через регулярные блоки.' },
        intensive: { title: 'Интенсивный', text: 'Для уже устойчивого ритма и низкого риска отвлечений.' },
      },
      focus: 'Фокус-блок',
      blocks: 'Блоков в день',
      volume: 'Полная продуктивность',
      tasks: 'Лимит действий',
      explanation: 'Почему так: система оставляет резерв, чтобы один сложный день не разрушил всю неделю.',
    },
    goal: {
      label: 'Система · цель недели',
      title: '7 дней. Один видимый результат.',
      text: 'Не «стать дисциплинированнее», а завершить конкретное действие, которое можно проверить.',
      goalLabel: 'Результат недели',
      goalPlaceholder: 'Например: подготовить и отправить первую версию предложения клиенту',
      criterionLabel: 'Как будет понятно, что результат получен?',
      criterionPlaceholder: 'Ссылка, отправленное письмо, опубликованная версия или другой факт',
      whyLabel: 'Почему это важно сейчас?',
      whyPlaceholder: 'Коротко: что изменится после результата',
      rule: 'Одна неделя · один главный внешний результат · без параллельной перестройки всей жизни.',
    },
    day: {
      label: 'Система · первый день',
      title: 'Ваш первый день уже собран.',
      text: 'В расписании остаётся один главный фокус, подготовка и фиксация результата. Остальное не получает статус обязательного.',
      start: 'Начать в',
      dailyResult: 'Результат дня',
      minimum: 'Минимум при сложном дне',
      minimumValue: 'Открыть рабочий материал и сделать первые 10 минут без переключений.',
      timeline: {
        prepare: 'Подготовить среду',
        prepareText: 'Убрать телефон, закрыть ленты, открыть один рабочий материал.',
        focus: 'Главный фокус',
        focusText: 'Один измеримый фрагмент недельного результата.',
        capture: 'Зафиксировать факт',
        captureText: 'Сохранить результат и отметить отвлечения без самооценки.',
      },
    },
    focus: {
      label: 'Первый цикл · фокус',
      title: 'Сейчас — только одно действие.',
      text: 'Любое желание переключиться сначала фиксируется. Срочное можно обработать, несрочное остаётся до конца блока.',
      idle: 'Готов к старту',
      running: 'Фокус идёт',
      done: 'Сессия завершена',
      start: 'Запустить фокус',
      stop: 'Завершить демо-сессию',
      mark: 'Отметить отвлечение',
      marked: 'Отвлечений отмечено: {count}',
      guard: 'Телефон вне зоны руки · одна вкладка · уведомления отключены',
    },
    review: {
      label: 'Первый цикл · честный разбор',
      title: 'Оцениваем действие. Не вас.',
      text: 'Разбор нужен, чтобы изменить завтра, а не объяснить вчера.',
      resultTitle: 'Что произошло с главным действием?',
      outcomes: [
        { id: 'completed', title: 'Результат получен', text: 'Намеченный фрагмент готов.' },
        { id: 'partial', title: 'Есть часть результата', text: 'Работа начата, но критерий не закрыт.' },
        { id: 'failed', title: 'Действие не выполнено', text: 'Фактического продвижения нет.' },
      ],
      fact: 'Что реально сработало или помешало?',
      factPlaceholder: 'Один конкретный факт без общих оценок себя',
      plan: 'Что изменить завтра?',
      planPlaceholder: 'Убрать фактор, сократить блок или точнее определить результат',
      planned: 'План',
      actual: 'Факт',
      distractions: 'Отвлечения',
    },
    adaptation: {
      label: 'День 1 из 7 завершён',
      maintainTitle: 'Режим сохранён',
      maintainText: 'Первый факт положительный, но одного дня недостаточно для повышения. Система проверит повторяемость.',
      reduceTitle: 'Нагрузка снижена',
      reduceText: 'Система сохраняет цель, но уменьшает следующий фокус-блок и число обязательных действий.',
      recoveryTitle: 'Завтра — восстановление',
      recoveryText: 'Цель не отменена. Завтра остаётся один минимальный шаг и восстановление ресурса.',
      reason: 'Решение принято по фактам',
      tomorrow: 'Параметры на завтра',
      focus: 'Фокус',
      volume: 'Продуктивный объём',
      actions: 'Обязательных действий',
      whyReturn: 'Завтра Life OS откроется сразу на плане дня и покажет только следующий шаг.',
    },
  },
  en: {
    eyebrow: 'Life OS · system setup',
    prototypeNote: 'Interactive prototype · data is not saved',
    progress: 'Step {current} of {total}',
    back: 'Back',
    next: 'Continue',
    finish: 'Restart prototype',
    required: 'Answer the question so the system can continue setup.',
    phases: [
      { title: 'Entry', detail: 'Context and readiness' },
      { title: 'Diagnosis', detail: 'Behavior, sabotage, distraction' },
      { title: 'Profile', detail: 'Capacity and workload' },
      { title: 'System', detail: 'Weekly result and first day' },
      { title: 'First loop', detail: 'Focus, review, adaptation' },
    ],
    stepNames: ['Sign up', 'Readiness', 'Real rhythm', 'Sabotage', 'Distractions', 'Capacity', 'Profile', 'Mode', 'Weekly goal', 'First day', 'Focus', 'Review', 'Adaptation'],
    entry: {
      label: 'Begin with an honest baseline',
      title: 'Not another task list. A system that accounts for where you break rhythm.',
      text: 'Life OS studies your routine, distractions, and real capacity first. It then suggests a workload you can repeat and adjusts it from daily evidence.',
      valueTitle: 'What happens after sign up',
      values: ['Complete a deep diagnosis without shame.', 'Receive an explainable discipline profile and starting mode.', 'Build a weekly result, first day, and focus session.'],
      email: 'Email', emailPlaceholder: 'you@example.com', password: 'Password', passwordPlaceholder: 'At least 8 characters',
      consent: 'I understand that change requires honest answers and personal action.',
      privacy: 'This prototype does not create an account or send any data.',
    },
    commitment: {
      label: 'Contract with yourself',
      title: 'The system will reveal patterns. You will still do the work.',
      text: 'Life OS does not promise instant motivation. It limits overload, returns to facts, and recommends the next manageable action.',
      agreement: 'I am ready to answer honestly, even when I dislike the answer.',
      principles: [
        { title: 'Self-control', text: 'Notice the impulse to switch before acting automatically.' },
        { title: 'Responsibility', text: 'Separate external constraints from personal avoidance.' },
        { title: 'Gentle precision', text: 'Reduce workload without excuses and increase it only from stable evidence.' },
      ],
    },
    reality: {
      label: 'Diagnosis · real rhythm', title: 'How often do you keep your own plan for at least five days?', text: 'Use a normal month, not the best period of your life.',
      options: [
        { id: 'rare', title: 'Almost never', text: 'I usually stop after one or two days.' },
        { id: 'sometimes', title: 'Sometimes', text: 'I hold for several days and then lose rhythm.' },
        { id: 'often', title: 'Often', text: 'Structure holds until workload spikes.' },
        { id: 'stable', title: 'Consistently', text: 'I complete most weeks as planned.' },
      ],
    },
    sabotage: {
      label: 'Diagnosis · sabotage', title: 'What usually happens before an important action?', text: 'Choose several. There is no correct answer.',
      options: [
        { id: 'delay', title: 'Delay the start', text: 'I wait for the right state or an open window.' },
        { id: 'perfectionism', title: 'Make it harder', text: 'I raise the standard and do not start until perfectly ready.' },
        { id: 'planning', title: 'Keep planning', text: 'I refine the system instead of taking the first irreversible step.' },
        { id: 'learning', title: 'Learn instead of practice', text: 'I open more material when the next action is already clear.' },
        { id: 'switch', title: 'Do something else', text: 'I complete small tasks to feel busy.' },
        { id: 'overload', title: 'Plan beyond capacity', text: 'I create a day that cannot be completed.' },
      ],
    },
    distractions: {
      label: 'Diagnosis · attention', title: 'Where does your attention go during work?', text: 'Include distractions that look useful.',
      options: [
        { id: 'gadget', title: 'Phone and notifications', text: 'I reach for a device without urgency.' },
        { id: 'social', title: 'Feeds and messages', text: 'I switch to social or information platforms.' },
        { id: 'research', title: 'Topic research', text: 'I look for one more source instead of executing.' },
        { id: 'otherTasks', title: 'Other tasks', text: 'I move to another task before finishing.' },
        { id: 'busywork', title: 'Busywork', text: 'I sort, style, and configure instead of producing output.' },
        { id: 'internal', title: 'Internal noise', text: 'I drift into thoughts, anxiety, or self-evaluation.' },
      ],
    },
    capacity: {
      label: 'Diagnosis · capacity', title: 'How much focused work is realistic now?', text: 'We do not need your maximum. We need something repeatable tomorrow.',
      focus: 'One distraction-free block', daily: 'Total productive work today', minutes: '{value} min', energyTitle: 'Usual energy level',
      energy: [
        { id: 'low', title: 'Low', text: 'I often begin already tired.' },
        { id: 'variable', title: 'Variable', text: 'It changes significantly by day.' },
        { id: 'stable', title: 'Stable', text: 'I can usually plan my capacity.' },
      ],
    },
    profile: {
      label: 'Discipline profile', dominantLabel: 'Dominant profile', basisTitle: 'Calculation basis', title: 'Your starting point should be lighter than your ambition, but stricter than habitual avoidance.', text: 'This is not a personality diagnosis. It is a working configuration based on your answers.',
      profiles: {
        depleted: { name: 'Low-resource mode', insight: 'Available energy is the main constraint now. The first mode should restore capacity while preserving one minimum mandatory step.', scenario: { start: 'Complete one mandatory ten-minute step. Everything else comes after it.', focus: 'Remove notifications and finish one short block without chasing the whole plan.', setback: 'Do not compensate with volume; return to the minimum step and recovery.' } },
        overloaded: { name: 'Overloaded system builder', insight: 'The planned standard and volume exceed repeatable capacity. The first mode should reduce load and restore consistency without abandoning the result.', scenario: { start: 'Choose one external result and remove everything that does not support it today.', focus: 'Use no more than two blocks; capture new tasks without switching to them.', setback: 'Reduce volume instead of extending the day or punishing yourself.' } },
        avoidant: { name: 'Cautious starter', insight: 'The main gap appears before action begins. The first mode should lower the start threshold and secure one short mandatory step.', scenario: { start: 'Begin within five minutes without additional preparation.', focus: 'Keep the first block short and judge the fact of starting, not output quality.', setback: 'Use a two-minute entry and record exactly what stopped the action.' } },
        perfectionist: { name: 'Perfectionist at the start', insight: 'The requirement to do it correctly raises the start threshold. The first mode should define a good-enough result and limit preparation.', scenario: { start: 'Define a good-enough criterion and a result that can be sent.', focus: 'Timebox preparation, then move to a draft without another review cycle.', setback: 'Lower the quality standard instead of postponing the whole action.' } },
        analytical: { name: 'Pre-start researcher', insight: 'Preparation and information gathering are starting to replace execution. The first mode should separate useful research from an already clear action.', scenario: { start: 'Keep only one question that genuinely blocks action.', focus: 'Research for at most ten minutes, then create the first verifiable fragment.', setback: 'Do not search for a new method; return to the next action already understood.' } },
        busywork: { name: 'Busy without output', insight: 'Activity is absorbed by formatting, sorting, and small tasks. The first mode should require one externally verifiable result instead of a feeling of busyness.', scenario: { start: 'Name one result that can be shown to another person.', focus: 'No formatting or small tasks before the primary result exists.', setback: 'Remove one pseudo-task and return that time to the primary result.' } },
        fragmented: { name: 'Fragmented executor', insight: 'You can act, but attention breaks across switches. The first mode should remove extra inputs and preserve one visible result.', scenario: { start: 'Close extra tabs and keep one channel, one document, and one task.', focus: 'Keep the phone out of reach; mark switching impulses without acting on them.', setback: 'Shorten the next block and remove the source of the latest distraction.' } },
        building: { name: 'Rhythm builder', insight: 'No single failure dominates, but the rhythm is not repeatable yet. The first mode should establish one simple support and test its stability.', scenario: { start: 'Anchor one recurring time and one repeatable first step.', focus: 'Keep the same block structure for three days without adding complexity.', setback: 'Return to the last completed version of the mode without new rules.' } },
        stable: { name: 'Stable executor', insight: 'Rhythm, energy, and capacity already support systematic work. The first mode can be more intensive, while increases still require evidence.', scenario: { start: 'Choose one priority result and block the main work interval for it.', focus: 'Use a full block without notifications; increase difficulty only after stable days.', setback: 'Keep the rhythm by reducing volume one step instead of cancelling the day.' } },
      },
      markers: { rhythm: 'Actual rhythm', sabotage: 'Sabotage', distractions: 'Distractions', capacity: 'Capacity' },
      more: '{count} more', capacityEvidence: '{energy} · {focus} min / {daily} min',
      insightTitle: 'Primary observation',
      scenarioTitle: 'How Life OS will change your start',
      scenarioLabels: { start: 'First action', focus: 'Focus protection', setback: 'If the day breaks' },
    },
    program: {
      label: 'System recommendation', title: 'Choose a start, but do not confuse difficulty with commitment.', text: 'The recommended mode is based on current capacity. It increases only after stable evidence.', recommended: 'Recommended', selected: 'Selected',
      modes: { gentle: { title: 'Gentle entry', text: 'Restore repetition and remove overload.' }, base: { title: 'Base rhythm', text: 'Build discipline through regular blocks.' }, intensive: { title: 'Intensive', text: 'For stable rhythm and low distraction risk.' } },
      focus: 'Focus block', blocks: 'Blocks per day', volume: 'Full productivity', tasks: 'Action limit', explanation: 'Why: the system preserves reserve so one hard day does not destroy the week.',
    },
    goal: {
      label: 'System · weekly goal', title: 'Seven days must produce an observable result.', text: 'Not “be more disciplined,” but complete an action that can be verified.',
      goalLabel: 'Weekly result', goalPlaceholder: 'Example: prepare and send the first client proposal draft', criterionLabel: 'How will you know it is done?', criterionPlaceholder: 'A link, sent email, published version, or another fact', whyLabel: 'Why now?', whyPlaceholder: 'Briefly: what changes after this result', rule: 'One week · one primary external result · no parallel rebuilding of your whole life.',
    },
    day: {
      label: 'System · first day', title: 'Your first day is already placed on a timeline.', text: 'The schedule keeps one main focus, preparation, and result capture. Everything else is optional.', start: 'Start at', dailyResult: 'Daily result', minimum: 'Minimum on a hard day', minimumValue: 'Open the work material and spend the first 10 minutes without switching.',
      timeline: { prepare: 'Prepare the environment', prepareText: 'Move the phone, close feeds, open one work surface.', focus: 'Primary focus', focusText: 'One measurable piece of the weekly result.', capture: 'Capture evidence', captureText: 'Save the output and record distractions without self-judgment.' },
    },
    focus: {
      label: 'First loop · focus', title: 'Only one action exists right now.', text: 'Any impulse to switch is recorded first. Urgent matters can be handled; everything else waits.', idle: 'Ready to start', running: 'Focus running', done: 'Session complete', start: 'Start focus', stop: 'Finish demo session', mark: 'Record distraction', marked: 'Distractions recorded: {count}', guard: 'Phone out of reach · one tab · notifications off',
    },
    review: {
      label: 'First loop · honest review', title: 'Evaluate the action, not your identity.', text: 'Review exists to change tomorrow, not explain yesterday.', resultTitle: 'What happened with the main action?',
      outcomes: [
        { id: 'completed', title: 'Result achieved', text: 'The planned piece is complete.' },
        { id: 'partial', title: 'Partial result', text: 'Work started but the criterion is open.' },
        { id: 'failed', title: 'Not completed', text: 'No observable progress.' },
      ],
      fact: 'What actually helped or blocked you?', factPlaceholder: 'One concrete fact without judging yourself', plan: 'What changes tomorrow?', planPlaceholder: 'Remove a factor, shorten the block, or clarify the result', planned: 'Plan', actual: 'Actual', distractions: 'Distractions',
    },
    adaptation: {
      label: 'Day 1 of 7 complete', maintainTitle: 'Mode maintained', maintainText: 'The first signal is positive, but one day is not enough to increase. The system will test repeatability.', reduceTitle: 'Workload slightly reduced', reduceText: 'The system keeps the goal but shortens the next focus block and mandatory list.', recoveryTitle: 'Recovery day enabled', recoveryText: 'The goal remains. Tomorrow includes one minimum step and capacity recovery.', reason: 'Decision based on evidence', tomorrow: 'Tomorrow parameters', focus: 'Focus', volume: 'Productive volume', actions: 'Mandatory actions', whyReturn: 'Tomorrow Life OS opens directly on the day plan and shows only the next action.',
    },
  },
} as const;

export type ActivationLocale = keyof typeof activationCopy;
